id = "jina-reader-extension"
name = "Jina Reader Extension"
version = "0.1.1"
schema_version = 1
authors = ["Alex Osipenko <alexey@ability.ai>", "Serhii Konev <sergey@cimon.io>"]
description = "Fetches content from a URL using r.jina.ai and inserts it into the chat."
repository = "https://github.com/Abilityai/jina-reader-extension"

[slash_commands.r]
description = "Fetch content from a URL using r.jina.ai"
requires_argument = true
